volumes:
    postgres-data:
        external: true
services:
  events-api:
    build:
      context: ./events/api
      dockerfile: ./Dockerfile.dev
    ports:
    - "8000:8000"
    volumes:
      - ./events/api:/app
    depends_on:
      - postgres
    environment:
      PGHOST: databases
      PGDATABASE: events
      PGUSER: events
      PGPASSWORD: events
  react:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
        - ./ghi/app:/app
    ports:
        - "3000:3000"
    environment:
        HOST_OS: ${OS}
        NODE_ENV: development
        HOST: "0.0.0.0"
  accounts-api:
    build:
      context: ./accounts/api
      dockerfile: ./Dockerfile.dev
    ports: 
    - "8001:8000"
    volumes:
      - ./accounts/api:/app
    depends_on:
      - postgres
    environment:
      PGHOST: databases
      PGDATABASE: accounts
      PGUSER: accounts
      PGPASSWORD: accounts

  postgres:
      build:
          context: ./relational-data
          dockerfile: ./Dockerfile.dev
      volumes:
          - postgres-data:/var/lib/postgresql/data
      environment:
          - POSTGRES_MULTIPLE_DATABASES= accounts, events
          - POSTGRES_PASSWORD=test-databases
      ports:
          - 15432:5432

    