volumes:
    postgres-data:
        external: true
services:
  events-api:
    build:
      context: ./events/api
      dockerfile: ./Dockerfile.dev
    ports:
    - "8000:8000"
    volumes:
      - ./events/api:/app
    depends_on:
      - postgres
    environment:
      PGHOST: databases
      PGDATABASE: events
      PGUSER: events
      PGPASSWORD: events
  react:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
        - ./ghi/app:/app
    ports:
        - "3000:3000"
    environment:
        HOST_OS: ${OS}
        NODE_ENV: development
        HOST: "0.0.0.0"
  accounts-api:
    build:
      context: ./accounts/api
      dockerfile: ./Dockerfile.dev
    ports: 
    - "8001:8000"
    volumes:
      - ./accounts/api:/app
    depends_on:
      - postgres
    environment:
      PGHOST: postgres
      PGDATABASE: puppin
      PGUSER: puppin
      PGPASSWORD: puppin

  postgres:
      build:
          context: ./relational-data
          dockerfile: ./Dockerfile.dev
      volumes:
          - ./data/postgres/init:/docker-entrypoint-initdb.d
          - postgres-data:/var/lib/postgresql/data
      environment:
        POSTGRES_PASSWORD: puppin
        POSTGRES_USER: puppin
        POSTGRES_DB: puppin
      ports:
          - 15432:5432

    